run-name: Updates

on:
  push:
    branches:
      - main
  
  #schedule:
  #  - cron: "3 6 * * *"

jobs:
  HAM22:
    name: HAM22
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 1
      matrix:
        detail: [19B]
        chain: [1, 2, 3, 4]

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute models
        run: |
          cd Code/
          cd Bayesian_model/
          python home_away_model_2.py d=${{ matrix.detail }} c=${{ matrix.chain }} > trash/HAM2_${{ matrix.detail }}_${{ matrix.chain }}.txt
          cd ../
          cd ../
      
      - name: Commit changes
        run: |
          git add *
          git pull
          git commit -m "Automated update (parameters sampling HAM2)"
          git push

