run-name: Updates

on:
  push:
    branches:
      - main
  
  schedule:
    - cron: "3 6 * * *"

jobs:
  Scrape:
    name: Scrape
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute scraping
        run: |
          cd Scrape/
          python main.py -s -a
          cd ../
          
      - name: Reindex players
        run: |
          cd Code/
          cd Commons/
          python script.py
          cd ../
          cd ../
          
      - name: Counts stats
        run: |
          cd Code/
          cd Graphs/
          python players_and_subgames.py > players_and_subgames.txt
          cd ../
          cd ../
                
      - name: Commit changes
        run: |
          git add *
          git commit -m "Automated update"
          git push

  Parameters:
    name: Parameters
    needs: Scrape
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        script: [atk_def_model.py, home_away_model.py, home_away_model_2.py]

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute models
        run: |
          cd Code/
          cd Bayesian_model/
          python ${{ matrix.script }}
          cd ../
          cd ../
      
      - name: Commit changes
        run: |
          git add *
          git pull
          git commit -m "Automated update (parameters sampling)"
          git push

