run-name: Ranking

on:
  push:
    branches:
      - main

jobs:
  Ranking:
    name: Ranking
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute models
        run: |
          cd Code/
          cd Bayesian_model/
          cd scripts/
          python best_players.py > ../stats/best_players.txt
          python best_clubs.py > ../stats/best_clubs.txt
          python plots.py
          cd ../
          cd ../
          cd ../
      
      - name: Commit changes
        run: |
          git add *
          git pull
          git commit -m "Automated update (Ranking and Plots)"
          git push

