on:
  schedule:
    - cron: schedule: "40 11 * * *" timezone: America/Sao_Paulo
    - cron: schedule: "45 11 * * *" timezone: America/Sao_Paulo
    - cron: schedule: "50 11 * * *" timezone: America/Sao_Paulo
    - cron: schedule: "55 11 * * *" timezone: America/Sao_Paulo
    - cron: schedule: "00 12 * * *" timezone: America/Sao_Paulo
jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute py script
        run: |
          cd Scrape/
          python main.py -s -a
          cd ../
      
      - name: Commit changes
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git add *
          git commit -m "Automated update"
          git push

