on:
  push:
    branches:
      - main
    paths:
      - Code/Bayesian_model/atk_def_model/**

jobs:
  Parameters_HAM:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute models
        run: |
          cd Code/
          cd Bayesian_model/
          python home_away_model.py
          cd ../
          cd ../
      
      - name: Commit changes
        run: |
          git pull
          git add *
          git commit -m "Automated update (parameters sampling - home away model)"
          git push

